import ctypes
import functools
import stat
import os
import subprocess
import threading
from pathlib import Path
from .proxy_domains import (
    get_dns_profiles,
    get_service_domain_ip_rows,
)
from .ipv6_detection import is_ipv6_address, is_ipv6_available
from .adobe_domains import ADOBE_DOMAINS
from log.log import log


#: Замок на цикл «прочитать hosts — поправить копию — записать целиком».
#:
#: Код, пишущий hosts, собран в одном модуле, но по времени писателей
#: бывает двое сразу: при запуске очередь «hosts» освежает адреса в
#: блоке net67, а «одна кнопка» в ту же секунду переприменяет
#: сохранённый выбор из своего потока. Каждый читает файл, правит свою
#: копию и пишет её поверх — без замка выигрывает дописавший последним,
#: а правка второго молча пропадает.
#:
#: RLock, а не Lock: обновление при запуске держит замок и изнутри зовёт
#: apply_service_dns_selections, который берёт его снова. Замок только
#: внутри процесса — второго net67 не даёт запустить защита от
#: повторного запуска.
HOSTS_EDIT_LOCK = threading.RLock()


def _serialized_hosts_edit(method):
    @functools.wraps(method)
    def wrapper(*args, **kwargs):
        with HOSTS_EDIT_LOCK:
            return method(*args, **kwargs)

    return wrapper


def _get_hosts_path_from_env() -> Path:
    """
    Возвращает путь к hosts через переменные окружения, чтобы корректно работать
    когда Windows установлена не на C:.
    """
    sys_root = os.environ.get("SystemRoot") or os.environ.get("WINDIR")
    if sys_root:
        return Path(sys_root, "System32", "drivers", "etc", "hosts")
    return Path(r"C:\Windows\System32\drivers\etc\hosts")


def _hosts_path() -> Path:
    """Путь к файлу hosts. Вне Windows — временный, а не выдуманный.

    Раньше здесь на любой не-Windows стоял тот же литерал
    ``C:\\Windows\\System32\\drivers\\etc\\hosts``. На Linux это не путь,
    а имя файла из одного куска с обратными слэшами: каждый прогон
    тестов, который трогает hosts, создавал такой файл в текущей папке.
    В корне репозитория он и обнаружился — прямо перед выкладкой, среди
    неотслеживаемых файлов.
    """
    if os.name == "nt":
        return _get_hosts_path_from_env()

    import tempfile

    return Path(tempfile.gettempdir()) / "net67-hosts-not-windows"


HOSTS_PATH = _hosts_path()

_MANAGED_HOSTS_BEGIN = "# >>> net67:hosts managed begin >>>"
_MANAGED_HOSTS_END = "# <<< net67:hosts managed end <<<"
_MANAGED_HOSTS_NOTICE = "# Generated by net67. Do not edit this block manually."

# Маркеры прежней версии приложения. Записываем всегда новые, но при чтении
# и очистке обязаны узнавать и старые: иначе блок, добавленный до
# переименования, останется в системном hosts навсегда — найти и удалить
# его будет уже нечем.
_LEGACY_MANAGED_HOSTS_BEGIN = "# >>> zapretgui:hosts managed begin >>>"
_LEGACY_MANAGED_HOSTS_END = "# <<< zapretgui:hosts managed end <<<"


def _is_managed_block_begin(stripped: str) -> bool:
    return stripped in (_MANAGED_HOSTS_BEGIN, _LEGACY_MANAGED_HOSTS_BEGIN)


def _is_managed_block_end(stripped: str) -> bool:
    return stripped in (_MANAGED_HOSTS_END, _LEGACY_MANAGED_HOSTS_END)


def _parse_hosts_mapping_line(line: str) -> tuple[str, list[str], str] | None:
    mapping_part, sep, comment_part = str(line or "").partition("#")
    mapping_stripped = mapping_part.strip()
    if not mapping_stripped:
        return None

    parts = mapping_stripped.split()
    if len(parts) < 2:
        return None

    ip = parts[0]
    domains = parts[1:]
    comment = comment_part.strip() if sep else ""
    return ip, domains, comment


def _remove_managed_hosts_block(lines: list[str]) -> tuple[list[str], int]:
    """Удаляет управляемый блок из hosts и возвращает строки без него."""
    new_lines: list[str] = []
    removed_entries = 0
    inside_block = False

    for line in lines:
        stripped = line.strip()
        if _is_managed_block_begin(stripped):
            inside_block = True
            continue
        if inside_block:
            if stripped and not stripped.startswith("#"):
                removed_entries += 1
            if _is_managed_block_end(stripped):
                inside_block = False
            continue
        new_lines.append(line)

    return new_lines, removed_entries


def _format_hosts_mapping_line(ip: str, domains: list[str], comment: str) -> str:
    line = f"{ip} {' '.join(domains)}"
    if comment:
        line += f" # {comment}"
    return line + "\n"


def _format_hosts_entries_count(count: int) -> str:
    count = int(count)
    if count % 10 == 1 and count % 100 != 11:
        word = "запись"
    elif count % 10 in (2, 3, 4) and count % 100 not in (12, 13, 14):
        word = "записи"
    else:
        word = "записей"
    return f"{count} {word}"


def _iter_managed_hosts_block_rows(lines: list[str]) -> list[tuple[str, str]]:
    """Возвращает строки (domain, ip), которые лежат внутри блока net67."""
    rows: list[tuple[str, str]] = []
    inside_block = False

    for line in lines:
        stripped = line.strip()
        if _is_managed_block_begin(stripped):
            inside_block = True
            continue
        if not inside_block:
            continue
        if _is_managed_block_end(stripped):
            # Не break: блоков бывает больше одного. Пока BOM прятал маркер
            # первого блока, каждая запись ставила рядом новый, и на живых
            # машинах их находили по два. Удаление снимает все блоки сразу —
            # и сравнивать надо со всеми, иначе устаревший первый блок
            # выглядел бы «пустым» и обновление его пропускало.
            inside_block = False
            continue
        if not stripped or stripped.startswith("#"):
            continue

        parsed = _parse_hosts_mapping_line(stripped)
        if parsed is None:
            continue
        ip, domains, _comment = parsed
        for domain in domains:
            rows.append((domain, ip))

    return rows


def _insert_managed_hosts_block(new_lines: list[str], rows: list[tuple[str, str]], insert_at: int | None = None) -> None:
    """Добавляет управляемый блок перед обычными строками hosts."""
    if not rows:
        return

    if insert_at is None:
        insert_at = len(new_lines)
        for index, line in enumerate(new_lines):
            if _parse_hosts_mapping_line(line) is not None:
                insert_at = index
                break
    insert_at = max(0, min(insert_at, len(new_lines)))

    while insert_at > 0 and new_lines[insert_at - 1].strip() == "":
        del new_lines[insert_at - 1]
        insert_at -= 1
    while insert_at < len(new_lines) and new_lines[insert_at].strip() == "":
        del new_lines[insert_at]

    block: list[str] = []
    if insert_at > 0 and new_lines[insert_at - 1].strip() != "":
        block.append("\n")
    block.append(f"{_MANAGED_HOSTS_BEGIN}\n")
    block.append(f"{_MANAGED_HOSTS_NOTICE}\n")
    for domain, ip in rows:
        block.append(f"{ip} {domain}\n")
    block.append(f"{_MANAGED_HOSTS_END}\n")
    if insert_at < len(new_lines) and new_lines[insert_at].strip() != "":
        block.append("\n")

    new_lines[insert_at:insert_at] = block


# ───────────────────────── hosts file read cache ─────────────────────────
#
# На старте приложение может несколько раз читать hosts подряд (проверки/страницы UI).
# Файл маленький, но повторные чтения + перебор кодировок/обработка PermissionError
# могут давать заметную задержку. Делаем безопасный кэш "на процесс":
# - инвалидируем по сигнатуре файла (mtime_ns + size)
# - обновляем кэш после успешной записи

_HOSTS_TEXT_CACHE: str | None = None
_HOSTS_SIG_CACHE: tuple[int, int] | None = None  # (mtime_ns, size)


def _get_hosts_sig(path: Path) -> tuple[int, int] | None:
    try:
        st = path.stat()
        mtime_ns = getattr(st, "st_mtime_ns", None)
        if mtime_ns is None:
            mtime_ns = int(st.st_mtime * 1_000_000_000)
        return (int(mtime_ns), int(st.st_size))
    except Exception:
        return None


def _set_hosts_cache(content: str | None, sig: tuple[int, int] | None) -> None:
    global _HOSTS_TEXT_CACHE, _HOSTS_SIG_CACHE
    _HOSTS_TEXT_CACHE = content
    _HOSTS_SIG_CACHE = sig


def invalidate_hosts_file_cache() -> None:
    """Принудительно сбрасывает кэш чтения hosts (на случай внешних изменений)."""
    _set_hosts_cache(None, None)


def _run_cmd(args, description):
    """Выполняет команду и логирует результат"""
    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        if result.returncode == 0:
            log(f"✅ {description}: успешно")
            return True
        else:
            # Проверяем stderr или stdout на наличие ошибки
            error = result.stderr.strip() or result.stdout.strip()
            log(f"⚠ {description}: {error}", "⚠ WARNING")
            return False
    except Exception as e:
        log(f"❌ {description}: {e}", "❌ ERROR")
        return False


def _get_current_username():
    """Получает имя текущего пользователя"""
    try:
        import getpass
        return getpass.getuser()
    except:
        return None


def restore_hosts_permissions():
    """
    Восстанавливает стандартные права доступа к файлу hosts.
    Устанавливает: Administrators:F, SYSTEM:F, Users:R (через SID для любой локализации).

    Вызывается ТОЛЬКО явно по кнопке пользователя в UI — не автоматически.
    Это НЕ вредоносная активность: пользователь сам нажал «Восстановить права доступа»,
    чтобы вернуть стандартные ACL на файл hosts после блокировки антивирусом.

    Returns:
        tuple: (success: bool, message: str)
    """
    hosts_path = str(HOSTS_PATH)

    # Действие инициировано пользователем через кнопку в интерфейсе приложения.
    # Восстанавливаем стандартные Windows ACL: Administrators:F, SYSTEM:F, Users:R.
    log("Пользователь запросил восстановление стандартных прав доступа к файлу hosts")

    # Well-known SIDs (работают на любой локализации Windows)
    SID_ADMINISTRATORS = "*S-1-5-32-544"  # Administrators
    SID_USERS = "*S-1-5-32-545"           # Users
    SID_SYSTEM = "*S-1-5-18"              # SYSTEM

    try:
        # Снимаем атрибут "только для чтения"
        _run_cmd(['attrib', '-R', hosts_path], "attrib -R")

        # Забираем владение для группы администраторов
        _run_cmd(['takeown', '/F', hosts_path, '/A'], "takeown /A")

        # Сбрасываем ACL и выставляем стандартные права через SID
        _run_cmd(['icacls', hosts_path, '/reset'], "icacls /reset")
        _run_cmd(['icacls', hosts_path, '/grant', f'{SID_ADMINISTRATORS}:F'],
                 "icacls /grant Administrators")
        _run_cmd(['icacls', hosts_path, '/grant', f'{SID_SYSTEM}:F'],
                 "icacls /grant SYSTEM")
        _run_cmd(['icacls', hosts_path, '/grant', f'{SID_USERS}:R'],
                 "icacls /grant Users (read)")

        # Проверяем результат
        try:
            HOSTS_PATH.read_text(encoding='utf-8')
            log("Права восстановлены, файл hosts доступен для чтения")

            try:
                with HOSTS_PATH.open('a', encoding='utf-8-sig'):
                    pass
                log("Файл hosts доступен для записи")
                return True, "Права доступа к файлу hosts восстановлены"
            except PermissionError:
                return False, (
                    "Файл hosts доступен для чтения, но запись запрещена.\n"
                    "Возможные причины: защита антивируса/Defender.\n"
                    "Добавьте исключение для hosts или временно отключите защиту."
                )

        except PermissionError:
            return False, (
                "Не удалось восстановить права доступа.\n"
                "Попробуйте:\n"
                "1. Запустить программу от имени администратора\n"
                "2. Временно отключить антивирус\n"
                "3. Добавить исключение для файла hosts"
            )

        except Exception as e:
            return False, f"Ошибка при проверке прав: {e}"

    except FileNotFoundError as e:
        return False, f"Системная команда не найдена: {e}"
    except Exception as e:
        return False, f"Ошибка: {e}"

def check_hosts_file_name():
    """Проверяет правильность написания имени файла hosts"""
    hosts_dir = Path(r"C:\Windows\System32\drivers\etc")
    
    # ✅ НОВОЕ: Создаем директорию если её нет
    if not hosts_dir.exists():
        try:
            hosts_dir.mkdir(parents=True, exist_ok=True)
            log(f"Создана директория: {hosts_dir}")
        except Exception as e:
            log(f"Не удалось создать директорию: {e}", "❌ ERROR")
            return False, f"Не удалось создать директорию etc: {e}"
    
    # Сначала проверяем правильный файл hosts
    hosts_lower = hosts_dir / "hosts"
    if hosts_lower.exists():
        # Дополнительно проверяем кодировку файла
        try:
            hosts_lower.read_text(encoding="utf-8-sig")
            return True, None
        except UnicodeDecodeError:
            # Файл существует, но с проблемами кодировки
            log("Файл hosts существует, но содержит некорректные символы", level="⚠ WARNING")
            return False, "Файл hosts содержит некорректные символы и не может быть прочитан в UTF-8"
    
    # Если правильного файла нет, проверяем есть ли неправильный HOSTS
    hosts_upper = hosts_dir / "HOSTS"
    if hosts_upper.exists():
        log("Обнаружен файл HOSTS (с большими буквами) - это неправильно!", level="⚠ WARNING")
        return False, "Файл должен называться 'hosts' (с маленькими буквами), а не 'HOSTS'"
    
    # ✅ НОВОЕ: Если файла нет вообще - это нормально, мы его создадим
    return True, None  # Изменено с False на True

def is_file_readonly(filepath):
    """Проверяет, установлен ли атрибут 'только для чтения' у файла"""
    try:
        file_stat = os.stat(filepath)
        return not (file_stat.st_mode & stat.S_IWRITE)
    except Exception as e:
        log(f"Ошибка при проверке атрибутов файла: {e}")
        return False

def _strip_leading_bom(text: str) -> str:
    """Снимает все BOM в начале текста hosts.

    Файл пишется в utf-8-sig, а читается сперва как utf-8 — и BOM при
    таком чтении остаётся в тексте символом U+FEFF. Следующая запись
    ставила перед ним ещё один, так что BOM копились: на машине владельца
    их нашлось четыре, на рабочей — пять. Сами по себе они безвредны, но
    str.strip() U+FEFF за пробел не считает. Маркер блока net67 в первой
    строке файла переставал узнаваться — блок нельзя было ни обновить, ни
    удалить, и Windows продолжала брать из него устаревшие адреса.
    Снимаем все: запись вернёт ровно один.
    """
    return text.lstrip("\ufeff")


def safe_read_hosts_file():
    """Безопасно читает файл hosts с обработкой различных кодировок.

    Если файла нет, возвращает пустую строку и ничего не создаёт.
    """
    hosts_path = HOSTS_PATH

    # Fast path: используем кэш если файл не менялся.
    try:
        if hosts_path.exists():
            sig = _get_hosts_sig(hosts_path)
            if sig is not None and _HOSTS_SIG_CACHE == sig and _HOSTS_TEXT_CACHE is not None:
                return _HOSTS_TEXT_CACHE
    except Exception:
        pass
    
    # Чтение никогда не создаёт файл: создать hosts может только явная
    # запись. Раньше отсутствующий hosts здесь же создавался с образцом
    # Microsoft — и одно открытие страницы, которое только смотрит, писало
    # в системную папку.
    if not hosts_path.exists():
        log(f"Файл hosts не существует: {hosts_path}", "DEBUG")
        return ""

    # Если файл существует, пробуем прочитать с разными кодировками
    encodings = ['utf-8', 'utf-8-sig', 'cp1251', 'cp866', 'latin1']

    permission_error_occurred = False

    sig_before = _get_hosts_sig(hosts_path)
    for encoding in encodings:
        try:
            content = _strip_leading_bom(hosts_path.read_text(encoding=encoding))
            log(f"Файл hosts успешно прочитан с кодировкой: {encoding}")
            _set_hosts_cache(content, sig_before or _get_hosts_sig(hosts_path))
            return content
        except UnicodeDecodeError:
            continue
        except PermissionError as e:
            log(f"Ошибка при чтении файла hosts с кодировкой {encoding}: {e}")
            permission_error_occurred = True
            continue
        except Exception as e:
            log(f"Ошибка при чтении файла hosts с кодировкой {encoding}: {e}")
            continue

    if permission_error_occurred:
        log("Нет доступа к файлу hosts. Используйте кнопку «Восстановить права доступа».", "WARNING")

    # Если ни одна кодировка не подошла, пробуем с игнорированием ошибок
    try:
        content = _strip_leading_bom(hosts_path.read_text(encoding='utf-8', errors='ignore'))
        log("Файл hosts прочитан с игнорированием ошибок кодировки", level="⚠ WARNING")
        _set_hosts_cache(content, _get_hosts_sig(hosts_path))
        return content
    except Exception as e:
        log(f"Критическая ошибка при чтении файла hosts: {e}", "❌ ERROR")
        return None

def safe_write_hosts_file(content):
    """Безопасно записывает файл hosts с правильной кодировкой"""
    try:
        # Защиту «только чтение» сами не снимаем. Её ставят нарочно — человек
        # или антивирус, — а страница hosts обещает, что программа её не
        # трогает. Снять можно кнопкой «Восстановить права доступа».
        if HOSTS_PATH.exists() and is_file_readonly(HOSTS_PATH):
            log("Файл hosts защищён от записи (только чтение). Используйте кнопку «Восстановить права доступа».", "WARNING")
            return False

        HOSTS_PATH.write_text(content, encoding="utf-8-sig", newline='\n')
        _set_hosts_cache(content, _get_hosts_sig(HOSTS_PATH))
        return True
    except PermissionError:
        log("Нет прав на запись в файл hosts. Используйте кнопку «Восстановить права доступа».", "WARNING")
        return False
    except Exception as e:
        log(f"Ошибка при записи файла hosts: {e}")
        return False
    
def _rows_from_fallback_profile(service_name: str, missing_profile: str) -> list[tuple[str, str]]:
    """Адреса сервиса из запасного профиля, если сохранённый исчез из каталога.

    Каталог обновляется вместе с программой, и профили в нём не вечны:
    в сентябре 2026 исходный проект убрал play2go.cloud DNS. У того, кто
    выбрал его на странице «Сервисы», сервис после обновления молча
    выпадал из hosts — выбор сохранён, а адресов под него больше нет.

    Берём тот же профиль, что и умолчания (XBOX DNS), а если его у
    сервиса нет — первый доступный. Выбор человека в настройках не
    трогаем: подмена только на эту запись.
    """
    try:
        from .defaults import choose_profile
        from .proxy_domains import get_service_available_dns_profiles, prefer_measured_profiles

        fallback = choose_profile(
            prefer_measured_profiles(service_name, get_service_available_dns_profiles(service_name))
        )
    except Exception as exc:
        log(f"Запасной профиль для «{service_name}» не выбран: {exc}", "DEBUG")
        return []
    if not fallback or fallback == missing_profile:
        return []
    rows = get_service_domain_ip_rows(service_name, fallback)
    if rows:
        log(
            f"Профиля «{missing_profile}» у «{service_name}» больше нет в каталоге — "
            f"записываю адреса профиля «{fallback}»",
            "INFO",
        )
    return rows


def _in_catalog_order(service_dns: dict[str, str] | None) -> list[tuple[str, str]]:
    """Выбор «сервис → профиль» в порядке каталога, а не словаря.

    Страница hosts записывала блок в порядке каталога, а сверка при запуске
    строила строки в порядке сохранённого выбора — он другой. Набор строк
    совпадал, порядок нет, и после каждого «Применить» следующий запуск
    переписывал весь блок, сообщая в журнал об «устаревших адресах», которых
    не было. Порядок значит и больше: у общего для двух сервисов домена
    побеждает сервис, идущий позже, — от порядка словаря зависел адрес.
    Сервисы, которых в каталоге нет, идут в конце в своём порядке.
    """
    items = [(name, profile) for name, profile in (service_dns or {}).items()]
    try:
        from .proxy_domains import get_services_profile_index

        position = {name: index for index, name in enumerate(get_services_profile_index().get("services") or [])}
    except Exception:
        return items
    tail = len(position)
    return sorted(items, key=lambda item: position.get(item[0], tail))


def _build_service_selection_rows(
    service_dns: dict[str, str],
    static_enabled: set[str] | None = None,
) -> tuple[list[tuple[str, str]], bool]:
    """Строки hosts из выбора «сервис → профиль» по текущему каталогу.

    Возвращает (строки domain/ip по порядку, был ли выбран хоть один
    профиль). Одна функция и для записи, и для сверки при запуске: иначе
    сверка считала бы строки не так, как их пишет запись, и блок
    переписывался бы на каждом старте.
    """
    # key = normalized domain; value = (display_domain, [ip1, ip2, ...]).
    selected_by_domain: dict[str, tuple[str, list[str]]] = {}
    domain_order: list[str] = []
    requested_any_profile = False

    def merge_rows(rows: list[tuple[str, str]]) -> None:
        per_service: dict[str, tuple[str, list[str], set[str]]] = {}
        per_service_order: list[str] = []

        for domain, ip in rows:
            domain_s = (domain or "").strip()
            ip_s = (ip or "").strip()
            if not domain_s or not ip_s:
                continue

            domain_key = domain_s.casefold()
            ip_key = ip_s.casefold()
            item = per_service.get(domain_key)
            if item is None:
                per_service[domain_key] = (domain_s, [ip_s], {ip_key})
                per_service_order.append(domain_key)
                continue

            display_domain, ips, seen_ips = item
            if ip_key in seen_ips:
                continue
            ips.append(ip_s)
            seen_ips.add(ip_key)
            per_service[domain_key] = (display_domain, ips, seen_ips)

        for domain_key in per_service_order:
            display_domain, ips, _seen_ips = per_service[domain_key]
            if domain_key not in selected_by_domain:
                domain_order.append(domain_key)
            # Keep old override semantics between services: later service replaces domain mapping.
            selected_by_domain[domain_key] = (display_domain, ips)

    for service_name, profile_name in _in_catalog_order(service_dns):
        if not isinstance(service_name, str):
            continue
        if not isinstance(profile_name, str):
            continue

        normalized = profile_name.strip().lower()
        if not normalized or normalized in ("off", "откл", "откл.", "0", "false"):
            continue

        requested_any_profile = True
        rows = get_service_domain_ip_rows(service_name, profile_name.strip())
        if not rows:
            rows = _rows_from_fallback_profile(service_name, profile_name.strip())
        if not rows:
            # Профиль недоступен для сервиса и заменить его нечем — пропускаем.
            continue
        merge_rows(rows)

    if static_enabled:
        default_profile = (get_dns_profiles() or [None])[0]
        for service_name in static_enabled:
            rows = get_service_domain_ip_rows(service_name, default_profile) if default_profile else []
            if rows:
                merge_rows(rows)

    selected_rows: list[tuple[str, str]] = []
    for domain_key in domain_order:
        display_domain, ips = selected_by_domain.get(domain_key, ("", []))
        for ip in ips:
            selected_rows.append((display_domain, ip))

    return selected_rows, requested_any_profile


def _hosts_rows_key(rows) -> list[tuple[str, str]]:
    return [(str(domain).strip().casefold(), str(ip).strip().casefold()) for domain, ip in rows]


def _filter_rows_for_ipv6(rows: list[tuple[str, str]], *, allow_ipv6: bool) -> list[tuple[str, str]]:
    """Те же чистки, что делает запись: повторы и IPv6 без поддержки IPv6."""
    result: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for domain, ip in rows:
        domain_s, ip_s = str(domain).strip(), str(ip).strip()
        if not domain_s or not ip_s:
            continue
        if is_ipv6_address(ip_s) and not allow_ipv6:
            continue
        key = (domain_s.casefold(), ip_s.casefold())
        if key in seen:
            continue
        seen.add(key)
        result.append((domain_s, ip_s))
    return result


def decide_applied_selection_refresh(
    *,
    block_rows: list[tuple[str, str]],
    has_saved_selection: bool,
    ipv6_available: bool,
    build_desired_rows,
) -> tuple[bool, str]:
    """Нужно ли при запуске переписать блок net67 в hosts.

    Каталог обновляется вместе с программой, и адреса в нём меняются: в
    сентябре 2026 у Claude, ChatGPT и почти всех сервисов с подменой DNS
    сменились адреса прокси. У того, кто уже включил сервис, в hosts
    остались старые — и до нажатия «Включить» новые туда не попадали.

    Переписываем, только если человек уже применял выбор (блок есть и
    выбор сохранён) и адреса в блоке отличаются от каталога. Решение взято
    из исходного проекта, где эту же задачу закрыли в 21.1.6.26.
    """
    if not block_rows:
        return False, "блока net67 в hosts нет"
    if not has_saved_selection:
        return False, "выбор сервисов не сохранён"
    if not ipv6_available and any(is_ipv6_address(ip) for _domain, ip in block_rows):
        # IPv6 мог просто ещё не подняться при запуске — не выкидываем IPv6-записи.
        return False, "IPv6 сейчас недоступен, а в блоке есть IPv6-записи"
    desired_rows = list(build_desired_rows() or [])
    if _hosts_rows_key(desired_rows) == _hosts_rows_key(block_rows):
        return False, "адреса в hosts уже актуальны"
    return True, "адреса в hosts устарели"


def _hosts_unavailable_status() -> str:
    """Почему hosts нельзя менять — словами, которые подсказывают выход.

    «Одна кнопка» показывает этот статус как есть. Общее «недоступен для
    изменения» при защите «только чтение» отправляло искать поломку не
    туда: права администратора у программы есть, мешает атрибут файла.
    """
    try:
        if HOSTS_PATH.exists() and is_file_readonly(HOSTS_PATH):
            return (
                "Файл hosts защищён от записи (стоит «только чтение»). "
                "Снимите защиту в меню страницы Hosts."
            )
    except Exception:
        pass
    return "Файл hosts недоступен для изменения"


class HostsManager:
    def __init__(self, status_callback=None):
        self.status_callback = status_callback
        self._last_status: str | None = None

    def restore_permissions(self):
        """Восстанавливает права доступа к файлу hosts"""
        success, message = restore_hosts_permissions()
        self.set_status(message)
        return success

    # ------------------------- сервис -------------------------
    def get_active_domains_map(self) -> dict[str, str]:
        """Возвращает {domain: ip} из блока net67 в системном hosts."""
        active_ip_map = self.get_active_domain_ip_map()
        current_active = {
            domain: ips[0]
            for domain, ips in active_ip_map.items()
            if ips
        }
        log(f"Найдено активных управляемых доменов: {len(current_active)}", "DEBUG")
        return current_active

    def get_active_domain_ip_map(self) -> dict[str, list[str]]:
        """Возвращает {domain: [ip, ...]} из блока net67 в системном hosts."""
        current_active_ips: dict[str, list[str]] = {}
        try:
            content = safe_read_hosts_file()
            if content is None:
                return current_active_ips

            for domain, ip in _iter_managed_hosts_block_rows(content.splitlines(keepends=True)):
                domain_key = (domain or "").casefold()
                ip_value = (ip or "").strip()
                if not domain_key or not ip_value:
                    continue
                values = current_active_ips.setdefault(domain_key, [])
                if ip_value not in values:
                    values.append(ip_value)

            active_rows = sum(len(values) for values in current_active_ips.values())
            log(f"Найдено активных управляемых hosts-записей: {active_rows}", "DEBUG")
        except Exception as e:
            log(f"Ошибка при чтении hosts: {e}", "ERROR")
        return current_active_ips

    def set_status(self, message: str):
        self._last_status = message
        if self.status_callback:
            self.status_callback(message)
        else:
            print(message)

    @property
    def last_status(self) -> str | None:
        return self._last_status

    # ------------------------- проверки -------------------------

    def is_proxy_domains_active(self) -> bool:
        """Проверяет, есть ли активные управляемые записи в hosts."""
        try:
            return bool(self.get_active_domains_map())
        except Exception as e:
            log(f"Ошибка при проверке hosts: {e}")
            return False

    def is_adobe_domains_active(self) -> bool:
        """Проверяет, есть ли активные записи Adobe в hosts"""
        try:
            content = safe_read_hosts_file()
            if content is None:
                return False
                
            lines = content.splitlines()
            domains = set(ADOBE_DOMAINS.keys())
            
            for line in lines:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                    
                parts = line.split()
                if len(parts) >= 2:
                    domain = parts[1]
                    if domain in domains:
                        return True
                        
            return False
        except Exception as e:
            log(f"Ошибка при проверке Adobe в hosts: {e}")
            return False

    def is_hosts_file_accessible(self) -> bool:
        """Проверяет, доступен ли файл hosts для чтения и записи."""
        try:
            # Проверяем правильность написания имени файла
            is_correct, error_msg = check_hosts_file_name()
            if not is_correct:
                log(error_msg)
                return False
            
            # Файла нет — его создаст сама запись. Пробный файл в etc больше не
            # пишем: проверка доступа не должна ничего менять в системной папке.
            if not HOSTS_PATH.exists():
                log("Файл hosts не существует, будет создан при записи")
                return True

            # Проверяем возможность чтения с безопасной функцией
            content = safe_read_hosts_file()
            if content is None:
                return False
                    
            if is_file_readonly(HOSTS_PATH):
                log("Файл hosts защищён от записи (только чтение)", "WARNING")
                return False

            # Проверяем право записи, не меняя содержимое.
            with HOSTS_PATH.open("a", encoding="utf-8-sig"):
                pass
            return True
            
        except PermissionError:
            log(f"Нет прав доступа к файлу hosts: {HOSTS_PATH}")
            return False
        except FileNotFoundError:
            log(f"Файл hosts не найден: {HOSTS_PATH}")
            return False
        except Exception as e:
            log(f"Ошибка при проверке доступности hosts: {e}")
            return False

    def is_hosts_file_readable(self) -> bool:
        """Проверяет, можно ли прочитать hosts без пробной записи в файл."""
        try:
            is_correct, error_msg = check_hosts_file_name()
            if not is_correct:
                log(error_msg)
                return False

            if not HOSTS_PATH.exists():
                log("Файл hosts не существует, для статуса считаем его пустым")
                return True

            content = safe_read_hosts_file()
            return content is not None
        except PermissionError:
            log(f"Нет прав на чтение файла hosts: {HOSTS_PATH}")
            return False
        except FileNotFoundError:
            log(f"Файл hosts не найден: {HOSTS_PATH}")
            return True
        except Exception as e:
            log(f"Ошибка при проверке чтения hosts: {e}")
            return False

    def _no_perm(self):
        """Обработка ошибки прав доступа"""
        self.set_status("Нет прав для изменения файла hosts")
        log("Нет прав для изменения файла hosts")

    @_serialized_hosts_edit
    def refresh_applied_service_selection(
        self,
        service_dns: dict[str, str],
        *,
        has_saved_selection: bool,
    ) -> tuple[bool, str]:
        """Обновляет адреса в уже записанном блоке net67 по свежему каталогу.

        Возвращает (переписан ли блок, причина). Ничего не пишет, если блока
        нет, выбор не сохранён или адреса и так совпадают.
        """
        content = safe_read_hosts_file()
        block_rows = _iter_managed_hosts_block_rows((content or "").splitlines(keepends=True))
        allow_ipv6 = is_ipv6_available() if block_rows else True

        def _desired_rows() -> list[tuple[str, str]]:
            rows, _requested = _build_service_selection_rows(service_dns)
            return _filter_rows_for_ipv6(rows, allow_ipv6=allow_ipv6)

        should_apply, reason = decide_applied_selection_refresh(
            block_rows=block_rows,
            has_saved_selection=has_saved_selection,
            ipv6_available=allow_ipv6,
            build_desired_rows=_desired_rows,
        )
        if not should_apply:
            log(f"Hosts при запуске: обновление не нужно ({reason})", "DEBUG")
            return False, reason
        if not self.apply_service_dns_selections(service_dns):
            reason = self.last_status or "не удалось переписать hosts"
            log(f"Hosts при запуске: не удалось обновить адреса: {reason}", "WARNING")
            return False, reason
        log("Hosts при запуске: устаревшие адреса в блоке net67 заменены по свежему каталогу", "INFO")
        return True, reason

    def apply_service_dns_selections(self, service_dns: dict[str, str], static_enabled: set[str] | None = None) -> bool:
        """
        Применяет выбор DNS-профилей по сервисам.

        Args:
            service_dns: {service_name: profile_name or 'off'}
            static_enabled: set(service_name) для сервисов, которые включаются без выбора профиля
        """
        log("🟡 apply_service_dns_selections начат", "DEBUG")

        selected_rows, requested_any_profile = _build_service_selection_rows(service_dns, static_enabled)

        if requested_any_profile and not selected_rows:
            self.set_status("Не найдено записей hosts для выбранных сервисов")
            log("apply_service_dns_selections: выбранные сервисы не дали записей hosts", "WARNING")
            return False

        return self.apply_domain_ip_rows(selected_rows)

    def apply_domain_ip_map(self, domain_ip_map: dict[str, str]) -> bool:
        """Применяет домены в hosts из словаря {domain: ip}."""
        rows: list[tuple[str, str]] = []
        for domain, ip in (domain_ip_map or {}).items():
            if not isinstance(domain, str) or not isinstance(ip, str):
                continue
            rows.append((domain, ip))
        return self.apply_domain_ip_rows(rows)

    @_serialized_hosts_edit
    def apply_domain_ip_rows(self, domain_ip_rows: list[tuple[str, str]]) -> bool:
        """Применяет домены в системный hosts через один управляемый управляемый блок."""
        log(f"🟡 apply_domain_ip_rows начат: {len(domain_ip_rows)} записей", "DEBUG")

        if not self.is_hosts_file_accessible():
            self.set_status(_hosts_unavailable_status())
            return False

        try:
            content = safe_read_hosts_file()
            if content is None:
                self.set_status("Не удалось прочитать файл hosts")
                return False

            lines = content.splitlines(keepends=True)
            new_lines, removed_count = _remove_managed_hosts_block(lines)

            # Убираем лишние пустые строки в конце
            while new_lines and new_lines[-1].strip() == "":
                new_lines.pop()

            allow_ipv6 = is_ipv6_available()
            desired_rows: list[tuple[str, str]] = []
            seen_rows: set[tuple[str, str]] = set()
            had_requested_rows = False
            for row in (domain_ip_rows or []):
                if not isinstance(row, (tuple, list)) or len(row) < 2:
                    continue
                domain = str(row[0]).strip()
                ip = str(row[1]).strip()
                if not domain or not ip:
                    continue
                had_requested_rows = True
                if is_ipv6_address(ip) and not allow_ipv6:
                    continue
                row_key = (domain.casefold(), ip.casefold())
                if row_key in seen_rows:
                    continue
                seen_rows.add(row_key)
                desired_rows.append((domain, ip))

            if had_requested_rows and not desired_rows:
                self.set_status("Нет подходящих hosts-записей для применения")
                log("apply_domain_ip_rows: все выбранные записи отфильтрованы перед записью", "WARNING")
                return False

            # Ничего не добавляем — просто очищаем управляемый блок
            if not desired_rows:
                if new_lines and not new_lines[-1].endswith("\n"):
                    new_lines[-1] += "\n"
                updated_content = "".join(new_lines)
                if updated_content == content:
                    self.set_status(f"Файл hosts уже актуален: удалено {removed_count} записей")
                    log("apply_domain_ip_rows: hosts уже актуален, запись пропущена", "DEBUG")
                    return True
                if not safe_write_hosts_file(updated_content):
                    return False
                self.set_status(f"Файл hosts обновлён: удалено {removed_count} записей")
                return True

            # Чужие строки с теми же доменами не трогаем. Раньше первая из них
            # вырезалась, а блок вставал на её место, — и черновик страницы,
            # показывающий «+N / −M строк» до записи, о таких удалениях молчал.
            # Блок встаёт перед первой записью файла, поэтому Windows всё равно
            # берёт адрес из него: при повторе домена побеждает верхняя строка.
            _insert_managed_hosts_block(new_lines, desired_rows)

            updated_content = "".join(new_lines)
            if updated_content == content:
                self.set_status(f"Файл hosts уже актуален: {_format_hosts_entries_count(len(desired_rows))}")
                log("apply_domain_ip_rows: hosts уже актуален, запись пропущена", "DEBUG")
                return True

            if not safe_write_hosts_file(updated_content):
                self.set_status("Не удалось записать файл hosts")
                return False

            self.set_status(f"Файл hosts обновлён: применено {_format_hosts_entries_count(len(desired_rows))}")
            log(
                f"✅ apply_domain_ip_rows: removed={removed_count}, added={len(desired_rows)}",
                "DEBUG",
            )
            return True

        except PermissionError:
            log("Ошибка прав доступа в apply_domain_ip_rows", "ERROR")
            self._no_perm()
            return False
        except Exception as e:
            log(f"Ошибка в apply_domain_ip_rows: {e}", "ERROR")
            return False

    # НОВЫЕ МЕТОДЫ ДЛЯ ADOBE
    @_serialized_hosts_edit
    def add_adobe_domains(self) -> bool:
        """Добавляет домены Adobe для блокировки активации"""
        log("🔒 Добавление доменов Adobe для блокировки активации", "DEBUG")
        
        if not self.is_hosts_file_accessible():
            self.set_status("Файл hosts недоступен для изменения")
            return False
        
        try:
            content = safe_read_hosts_file()
            if content is None:
                return False
            
            # Удаляем старые записи Adobe
            lines = content.splitlines(keepends=True)
            domains_to_remove = set(ADOBE_DOMAINS.keys())
            
            new_lines = []
            skip_adobe_comment = False
            for line in lines:
                # Пропускаем старый комментарий Adobe
                if "# Adobe Activation Block" in line or "# Adobe Block" in line:
                    skip_adobe_comment = True
                    continue
                if skip_adobe_comment and "# Generated by" in line:
                    skip_adobe_comment = False
                    continue
                    
                if (line.strip() and 
                    not line.lstrip().startswith("#") and 
                    len(line.split()) >= 2 and 
                    line.split()[1] in domains_to_remove):
                    continue
                new_lines.append(line)
            
            # Убираем лишние пустые строки
            while new_lines and new_lines[-1].strip() == "":
                new_lines.pop()
            
            # Добавляем новые домены Adobe
            if new_lines and not new_lines[-1].endswith('\n'):
                new_lines.append('\n')
            new_lines.append('\n')
            new_lines.append('# Adobe Activation Block\n')
            new_lines.append('# Generated by net67\n')
            
            for domain, ip in ADOBE_DOMAINS.items():
                new_lines.append(f"{ip} {domain}\n")
            
            # Записываем
            if not safe_write_hosts_file("".join(new_lines)):
                return False
            
            self.set_status(f"Блокировка Adobe активирована: добавлено {len(ADOBE_DOMAINS)} записей")
            log(f"✅ Добавлены домены Adobe для блокировки", "DEBUG")
            return True
            
        except PermissionError:
            log("Ошибка прав доступа при добавлении Adobe доменов", "ERROR")
            self._no_perm()
            return False
        except Exception as e:
            log(f"Ошибка при добавлении Adobe доменов: {e}", "ERROR")
            return False

    @_serialized_hosts_edit
    def clear_hosts_file(self) -> bool:
        """Удаляет только управляемый блок из системного hosts."""
        log("🗑️ Очистка блока net67 в hosts", "DEBUG")
        
        if not self.is_hosts_file_accessible():
            self.set_status("Файл hosts недоступен для изменения")
            return False
        
        try:
            content = safe_read_hosts_file()
            if content is None:
                return False

            new_lines, removed_count = _remove_managed_hosts_block(content.splitlines(keepends=True))
            while new_lines and new_lines[-1].strip() == "":
                new_lines.pop()
            if new_lines and not new_lines[-1].endswith("\n"):
                new_lines[-1] += "\n"
            
            if not safe_write_hosts_file("".join(new_lines)):
                log("Не удалось записать файл hosts после очистки блока net67")
                return False
            
            self.set_status(f"Блок net67 очищен: удалено {removed_count} записей")
            invalidate_hosts_file_cache()
            log(f"✅ Блок net67 в hosts очищен: удалено {removed_count} записей", "DEBUG")
            return True
            
        except PermissionError:
            log("Ошибка прав доступа при очистке hosts файла", "ERROR")
            self._no_perm()
            return False
        except Exception as e:
            log(f"Ошибка при очистке hosts файла: {e}", "ERROR")
            return False
        
    @_serialized_hosts_edit
    def remove_adobe_domains(self) -> bool:
        """Удаляет домены Adobe из hosts файла"""
        log("🔓 Удаление доменов Adobe", "DEBUG")
        
        if not self.is_hosts_file_accessible():
            self.set_status("Файл hosts недоступен для изменения")
            return False
        
        try:
            content = safe_read_hosts_file()
            if content is None:
                return False
            
            lines = content.splitlines(keepends=True)
            domains = set(ADOBE_DOMAINS.keys())
            
            new_lines = []
            removed_count = 0
            skip_next = False
            
            for line in lines:
                # Удаляем комментарии Adobe
                if "# Adobe Activation Block" in line or "# Adobe Block" in line:
                    skip_next = True
                    continue
                if skip_next and "# Generated by" in line:
                    skip_next = False
                    continue
                    
                if (line.strip() and 
                    not line.lstrip().startswith("#") and 
                    len(line.split()) >= 2 and 
                    line.split()[1] in domains):
                    removed_count += 1
                    continue
                    
                new_lines.append(line)
            
            # Убираем лишние пустые строки
            while new_lines and new_lines[-1].strip() == "":
                new_lines.pop()
            
            if new_lines and not new_lines[-1].endswith('\n'):
                new_lines.append('\n')
            
            if not safe_write_hosts_file("".join(new_lines)):
                return False
            
            self.set_status(f"Блокировка Adobe отключена: удалено {removed_count} записей")
            log(f"✅ Удалено {removed_count} доменов Adobe", "DEBUG")
            return True
            
        except PermissionError:
            log("Ошибка прав доступа при удалении Adobe доменов", "ERROR")
            self._no_perm()
            return False
        except Exception as e:
            log(f"Ошибка при удалении Adobe доменов: {e}", "ERROR")
            return False
