-- Auto-generated: preload strategies from settings.json
-- Generated: 2026-07-11 18:28:03
-- empty, History: 44

-- Blocked strategies (default + user-defined)
-- Function slm_is_blocked() is defined in strategy-lock-manager.lua
-- Format: slm_preload_blocked(askey, hostname, {strategies})
slm_preload_blocked("tls", "google.com", {1})
slm_preload_blocked("http", "google.com", {1})
slm_preload_blocked("mtproto", "google.com", {1})
slm_preload_blocked("tls", "facebook.com", {1})
slm_preload_blocked("http", "facebook.com", {1})
slm_preload_blocked("mtproto", "facebook.com", {1})
slm_preload_blocked("tls", "discord.gg", {1})
slm_preload_blocked("http", "discord.gg", {1})
slm_preload_blocked("mtproto", "discord.gg", {1})
slm_preload_blocked("tls", "google.ru", {1})
slm_preload_blocked("http", "google.ru", {1})
slm_preload_blocked("mtproto", "google.ru", {1})
slm_preload_blocked("tls", "whatsapp.net", {1})
slm_preload_blocked("http", "whatsapp.net", {1})
slm_preload_blocked("mtproto", "whatsapp.net", {1})
slm_preload_blocked("tls", "googleadservices.com", {1})
slm_preload_blocked("http", "googleadservices.com", {1})
slm_preload_blocked("mtproto", "googleadservices.com", {1})
slm_preload_blocked("tls", "tiktok.com", {1})
slm_preload_blocked("http", "tiktok.com", {1})
slm_preload_blocked("mtproto", "tiktok.com", {1})
slm_preload_blocked("tls", "twitter.com", {1})
slm_preload_blocked("http", "twitter.com", {1})
slm_preload_blocked("mtproto", "twitter.com", {1})
slm_preload_blocked("tls", "youtube.com", {1})
slm_preload_blocked("http", "youtube.com", {1})
slm_preload_blocked("mtproto", "youtube.com", {1})
slm_preload_blocked("tls", "tiktokcdn.com", {1})
slm_preload_blocked("http", "tiktokcdn.com", {1})
slm_preload_blocked("mtproto", "tiktokcdn.com", {1})
slm_preload_blocked("tls", "netflix.com", {1})
slm_preload_blocked("http", "netflix.com", {1})
slm_preload_blocked("mtproto", "netflix.com", {1})
slm_preload_blocked("tls", "roblox.com", {1})
slm_preload_blocked("http", "roblox.com", {1})
slm_preload_blocked("mtproto", "roblox.com", {1})
slm_preload_blocked("tls", "ytimg.com", {1})
slm_preload_blocked("http", "ytimg.com", {1})
slm_preload_blocked("mtproto", "ytimg.com", {1})
slm_preload_blocked("tls", "redditmedia.com", {1})
slm_preload_blocked("http", "redditmedia.com", {1})
slm_preload_blocked("mtproto", "redditmedia.com", {1})
slm_preload_blocked("tls", "instagram.com", {1})
slm_preload_blocked("http", "instagram.com", {1})
slm_preload_blocked("mtproto", "instagram.com", {1})
slm_preload_blocked("tls", "googlevideo.com", {1})
slm_preload_blocked("http", "googlevideo.com", {1})
slm_preload_blocked("mtproto", "googlevideo.com", {1})
slm_preload_blocked("tls", "ggpht.com", {1})
slm_preload_blocked("http", "ggpht.com", {1})
slm_preload_blocked("mtproto", "ggpht.com", {1})
slm_preload_blocked("tls", "twitch.tv", {1})
slm_preload_blocked("http", "twitch.tv", {1})
slm_preload_blocked("mtproto", "twitch.tv", {1})
slm_preload_blocked("tls", "cdninstagram.com", {1})
slm_preload_blocked("http", "cdninstagram.com", {1})
slm_preload_blocked("mtproto", "cdninstagram.com", {1})
slm_preload_blocked("tls", "reddit.com", {1})
slm_preload_blocked("http", "reddit.com", {1})
slm_preload_blocked("mtproto", "reddit.com", {1})
slm_preload_blocked("tls", "twitchcdn.net", {1})
slm_preload_blocked("http", "twitchcdn.net", {1})
slm_preload_blocked("mtproto", "twitchcdn.net", {1})
slm_preload_blocked("tls", "googleapis.com", {1})
slm_preload_blocked("http", "googleapis.com", {1})
slm_preload_blocked("mtproto", "googleapis.com", {1})
slm_preload_blocked("tls", "x.com", {1})
slm_preload_blocked("http", "x.com", {1})
slm_preload_blocked("mtproto", "x.com", {1})
slm_preload_blocked("tls", "spotify.com", {1})
slm_preload_blocked("http", "spotify.com", {1})
slm_preload_blocked("mtproto", "spotify.com", {1})
slm_preload_blocked("tls", "googletagmanager.com", {1})
slm_preload_blocked("http", "googletagmanager.com", {1})
slm_preload_blocked("mtproto", "googletagmanager.com", {1})
slm_preload_blocked("tls", "steamcommunity.com", {1})
slm_preload_blocked("http", "steamcommunity.com", {1})
slm_preload_blocked("mtproto", "steamcommunity.com", {1})
slm_preload_blocked("tls", "discordapp.com", {1})
slm_preload_blocked("http", "discordapp.com", {1})
slm_preload_blocked("mtproto", "discordapp.com", {1})
slm_preload_blocked("tls", "githubusercontent.com", {1})
slm_preload_blocked("http", "githubusercontent.com", {1})
slm_preload_blocked("mtproto", "githubusercontent.com", {1})
slm_preload_blocked("tls", "withyoutube.com", {1})
slm_preload_blocked("http", "withyoutube.com", {1})
slm_preload_blocked("mtproto", "withyoutube.com", {1})
slm_preload_blocked("tls", "googlesyndication.com", {1})
slm_preload_blocked("http", "googlesyndication.com", {1})
slm_preload_blocked("mtproto", "googlesyndication.com", {1})
slm_preload_blocked("tls", "googleusercontent.com", {1})
slm_preload_blocked("http", "googleusercontent.com", {1})
slm_preload_blocked("mtproto", "googleusercontent.com", {1})
slm_preload_blocked("tls", "discord.com", {1})
slm_preload_blocked("http", "discord.com", {1})
slm_preload_blocked("mtproto", "discord.com", {1})
slm_preload_blocked("tls", "discord.media", {1})
slm_preload_blocked("http", "discord.media", {1})
slm_preload_blocked("mtproto", "discord.media", {1})
slm_preload_blocked("tls", "igcdn.com", {1})
slm_preload_blocked("http", "igcdn.com", {1})
slm_preload_blocked("mtproto", "igcdn.com", {1})
slm_preload_blocked("tls", "steampowered.com", {1})
slm_preload_blocked("http", "steampowered.com", {1})
slm_preload_blocked("mtproto", "steampowered.com", {1})
slm_preload_blocked("tls", "redd.it", {1})
slm_preload_blocked("http", "redd.it", {1})
slm_preload_blocked("mtproto", "redd.it", {1})
slm_preload_blocked("tls", "musical.ly", {1})
slm_preload_blocked("http", "musical.ly", {1})
slm_preload_blocked("mtproto", "musical.ly", {1})
slm_preload_blocked("tls", "whatsapp.com", {1})
slm_preload_blocked("http", "whatsapp.com", {1})
slm_preload_blocked("mtproto", "whatsapp.com", {1})
slm_preload_blocked("tls", "fb.me", {1})
slm_preload_blocked("http", "fb.me", {1})
slm_preload_blocked("mtproto", "fb.me", {1})
slm_preload_blocked("tls", "rutracker.org", {1})
slm_preload_blocked("http", "rutracker.org", {1})
slm_preload_blocked("mtproto", "rutracker.org", {1})
slm_preload_blocked("tls", "youtube-nocookie.com", {1})
slm_preload_blocked("http", "youtube-nocookie.com", {1})
slm_preload_blocked("mtproto", "youtube-nocookie.com", {1})
slm_preload_blocked("tls", "withgoogle.com", {1})
slm_preload_blocked("http", "withgoogle.com", {1})
slm_preload_blocked("mtproto", "withgoogle.com", {1})
slm_preload_blocked("tls", "ig.me", {1})
slm_preload_blocked("http", "ig.me", {1})
slm_preload_blocked("mtproto", "ig.me", {1})
slm_preload_blocked("tls", "youtu.be", {1})
slm_preload_blocked("http", "youtu.be", {1})
slm_preload_blocked("mtproto", "youtu.be", {1})
slm_preload_blocked("tls", "google-analytics.com", {1})
slm_preload_blocked("http", "google-analytics.com", {1})
slm_preload_blocked("mtproto", "google-analytics.com", {1})
slm_preload_blocked("tls", "yt3.ggpht.com", {1})
slm_preload_blocked("http", "yt3.ggpht.com", {1})
slm_preload_blocked("mtproto", "yt3.ggpht.com", {1})
slm_preload_blocked("tls", "dns.google", {1})
slm_preload_blocked("http", "dns.google", {1})
slm_preload_blocked("mtproto", "dns.google", {1})
slm_preload_blocked("tls", "rbxcdn.com", {1})
slm_preload_blocked("http", "rbxcdn.com", {1})
slm_preload_blocked("mtproto", "rbxcdn.com", {1})
slm_preload_blocked("tls", "googleanalytics.com", {1})
slm_preload_blocked("http", "googleanalytics.com", {1})
slm_preload_blocked("mtproto", "googleanalytics.com", {1})
slm_preload_blocked("tls", "nflxvideo.net", {1})
slm_preload_blocked("http", "nflxvideo.net", {1})
slm_preload_blocked("mtproto", "nflxvideo.net", {1})
slm_preload_blocked("tls", "spotifycdn.com", {1})
slm_preload_blocked("http", "spotifycdn.com", {1})
slm_preload_blocked("mtproto", "spotifycdn.com", {1})
slm_preload_blocked("tls", "github.com", {1})
slm_preload_blocked("http", "github.com", {1})
slm_preload_blocked("mtproto", "github.com", {1})
slm_preload_blocked("tls", "steamstatic.com", {1})
slm_preload_blocked("http", "steamstatic.com", {1})
slm_preload_blocked("mtproto", "steamstatic.com", {1})
slm_preload_blocked("tls", "twimg.com", {1})
slm_preload_blocked("http", "twimg.com", {1})
slm_preload_blocked("mtproto", "twimg.com", {1})
slm_preload_blocked("tls", "fbcdn.net", {1})
slm_preload_blocked("http", "fbcdn.net", {1})
slm_preload_blocked("mtproto", "fbcdn.net", {1})
slm_preload_blocked("tls", "gstatic.com", {1})
slm_preload_blocked("http", "gstatic.com", {1})
slm_preload_blocked("mtproto", "gstatic.com", {1})
slm_preload_blocked("tls", "fb.com", {1})
slm_preload_blocked("http", "fb.com", {1})
slm_preload_blocked("mtproto", "fb.com", {1})
slm_preload_blocked("tls", "discordapp.net", {1})
slm_preload_blocked("http", "discordapp.net", {1})
slm_preload_blocked("mtproto", "discordapp.net", {1})
slm_preload_blocked("tls", "doubleclick.net", {1})
slm_preload_blocked("http", "doubleclick.net", {1})
slm_preload_blocked("mtproto", "doubleclick.net", {1})

slm_preload_locked("tls", "google.com", 2)
slm_preload_locked("tls", "ytimg.com", 2)
slm_preload_locked("tls", "discord.com", 3)
slm_preload_locked("tls", "discord.gg", 2)
slm_preload_locked("tls", "googleapis.com", 2)
slm_preload_history("tls", "google.com", 2, 0, 2)
slm_preload_history("tls", "havegreatday.co.uk", 1, 5, 0)
slm_preload_history("tls", "kartoshka.co.uk", 1, 5, 0)
slm_preload_history("tls", "steamcontent.com", 1, 16, 3)
slm_preload_history("tls", "steamcontent.com", 2, 1, 2)
slm_preload_history("tls", "steamcontent.com", 3, 0, 1)
slm_preload_history("tls", "nothingthere.co.uk", 1, 2, 1)
slm_preload_history("tls", "nothingthere.co.uk", 2, 1, 1)
slm_preload_history("tls", "nothingthere.co.uk", 3, 0, 1)
slm_preload_history("tls", "onedaychamp.co.uk", 1, 2, 1)
slm_preload_history("tls", "sadnews.co.uk", 1, 2, 0)
slm_preload_history("tls", "notelega.co.uk", 1, 0, 1)
slm_preload_history("tls", "notelega.co.uk", 2, 1, 0)
slm_preload_history("tls", "ebally.co.uk", 1, 8, 1)
slm_preload_history("tls", "pyatdesyatodin.co.uk", 1, 1, 1)
slm_preload_history("tls", "pyatdesyatodin.co.uk", 2, 2, 0)
slm_preload_history("tls", "sorokdva.co.uk", 1, 2, 0)
slm_preload_history("tls", "akamaized.net", 1, 7, 1)
slm_preload_history("tls", "akamaized.net", 2, 0, 1)
slm_preload_history("tls", "pclead.co.uk", 1, 2, 0)
slm_preload_history("tls", "ytimg.com", 2, 0, 2)
slm_preload_history("tls", "lovetrue.co.uk", 1, 3, 0)
slm_preload_history("tls", "sorokodin.co.uk", 1, 5, 1)
slm_preload_history("tls", "discord.com", 2, 1, 3)
slm_preload_history("tls", "discord.com", 3, 3, 1)
slm_preload_history("tls", "cloudflare.com", 2, 4, 0)
slm_preload_history("tls", "239.255.0.0", 1, 0, 6)
slm_preload_history("tls", "discord.gg", 2, 1, 1)
slm_preload_history("tls", "msn.com", 1, 9, 0)
slm_preload_history("tls", "nebally.co.uk", 1, 1, 0)
slm_preload_history("tls", "pyatdesyatdva.co.uk", 1, 1, 0)
slm_preload_history("tls", "windows.com", 1, 2, 0)
slm_preload_history("tls", "nvidia.com", 1, 4, 3)
slm_preload_history("tls", "googleapis.com", 2, 3, 0)
slm_preload_history("tls", "geforce.com", 1, 1, 1)
slm_preload_history("tls", "geforce.com", 2, 1, 1)
slm_preload_history("tls", "geforce.com", 3, 1, 1)
slm_preload_history("tls", "geforce.com", 4, 1, 1)
slm_preload_history("tls", "geforce.com", 5, 1, 1)
slm_preload_history("tls", "geforce.com", 6, 1, 1)
slm_preload_history("tls", "jsdelivr.net", 1, 1, 0)
slm_preload_history("tls", "xboxlive.com", 1, 1, 1)
slm_preload_history("tls", "xboxlive.com", 2, 1, 0)
slm_preload_history("tls", "ayugram.one", 1, 1, 0)
slm_preload_history("tls", "offshor.co.uk", 1, 4, 1)
slm_preload_history("tls", "offshor.co.uk", 2, 1, 1)
slm_preload_history("tls", "fixtelega.co.uk", 1, 1, 0)
slm_preload_history("tls", "sentry.io", 1, 2, 0)
slm_preload_history("tls", "155.133.0.0", 1, 6, 0)
slm_preload_history("tls", "162.254.0.0", 1, 3, 0)
slm_preload_history("tls", "185.25.0.0", 1, 2, 0)
slm_preload_history("tls", "146.66.0.0", 1, 2, 0)
slm_preload_history("tls", "gamepass.com", 1, 1, 1)
slm_preload_history("tls", "virtualearth.net", 1, 1, 0)

DLOG("learned-strategies: loaded 0 strategies + 44 history (blocked: 0)")

-- Install circular wrapper to apply preloaded strategies on first packet
install_circular_wrapper()
DLOG("learned-strategies: wrapper installed, circular=" .. tostring(circular ~= nil) .. ", original=" .. tostring(original_circular ~= nil))

-- DEBUG: extra wrapper to diagnose APPLIED issue
if circular and working_strategies then
    local _debug_circular = circular
    circular = function(ctx, desync)
        local hostname = standard_hostkey and standard_hostkey(desync) or "?"
        local askey = (desync and desync.arg and desync.arg.key and #desync.arg.key>0) and desync.arg.key or (desync and desync.func_instance or "?")
        local data = working_strategies[hostname]
        if data then
            local expected = get_autostate_key_by_payload and get_autostate_key_by_payload(data.payload_type) or "?"
            DLOG("DEBUG circular: host=" .. hostname .. " askey=" .. askey .. " expected=" .. expected .. " locked=" .. tostring(data.locked) .. " applied=" .. tostring(data.applied))
        end
        return _debug_circular(ctx, desync)
    end
    DLOG("learned-strategies: DEBUG wrapper installed")
end

-- Install blocked strategies filter for circular rotation
-- slm_is_blocked() is defined in strategy-lock-manager.lua
local _blocked_wrap_installed = false
local function install_blocked_filter()
    if _blocked_wrap_installed then return end
    _blocked_wrap_installed = true
    if circular and type(circular) == "function" then
        local original_circular = circular
        circular = function(t, hostname, ...)
            local result = original_circular(t, hostname, ...)
            if result and hostname and slm_is_blocked(hostname, result) then
                local max_skip = 10
                for i = 1, max_skip do
                    result = original_circular(t, hostname, ...)
                    if not result or not slm_is_blocked(hostname, result) then break end
                    DLOG("BLOCKED: skip strategy " .. result .. " for " .. hostname)
                end
            end
            return result
        end
        DLOG("Blocked strategies filter installed for circular")
    end
end
install_blocked_filter()
