"""BOM в начале hosts больше не копится и не прячет блок net67.

Файл пишется в utf-8-sig, а читается сперва как utf-8, и BOM оставался в
тексте символом U+FEFF — каждая запись добавляла ещё один. В копии hosts
владельца их было четыре, на рабочей машине пять. Когда блок net67 стоял
первой строкой файла, его маркер за BOM не узнавался: блок нельзя было ни
обновить, ни удалить, а рядом при каждой записи появлялся новый.
"""

import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import hosts.hosts as hosts_module  # noqa: E402

BOM = "﻿"
BEGIN = "# >>> net67:hosts managed begin >>>"
END = "# <<< net67:hosts managed end <<<"
NOTICE = "# Generated by net67. Do not edit this block manually."


class HostsBomTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.path = Path(self._tmp.name) / "hosts"
        patcher = mock.patch.object(hosts_module, "HOSTS_PATH", self.path)
        patcher.start()
        self.addCleanup(patcher.stop)
        self.addCleanup(self._tmp.cleanup)
        hosts_module.invalidate_hosts_file_cache()
        self.addCleanup(hosts_module.invalidate_hosts_file_cache)

    def _write(self, text: str) -> None:
        self.path.write_bytes(text.encode("utf-8"))
        hosts_module.invalidate_hosts_file_cache()

    def _manager(self):
        manager = hosts_module.HostsManager.__new__(hosts_module.HostsManager)
        manager.status_callback = None
        manager._last_status = None
        return manager

    def test_read_drops_every_leading_bom(self) -> None:
        self._write(BOM * 5 + f"{BEGIN}\n{NOTICE}\n87.228.47.204 claude.ai\n{END}\n")

        content = hosts_module.safe_read_hosts_file()

        self.assertFalse(content.startswith(BOM))
        rows = hosts_module._iter_managed_hosts_block_rows(content.splitlines(keepends=True))
        self.assertEqual(rows, [("claude.ai", "87.228.47.204")])

    def test_rows_are_collected_from_every_block(self) -> None:
        lines = [
            f"{BEGIN}\n",
            "87.228.47.204 claude.ai\n",
            f"{END}\n",
            "\n",
            f"{BEGIN}\n",
            "23.227.38.74 discord.com\n",
            f"{END}\n",
        ]

        rows = hosts_module._iter_managed_hosts_block_rows(lines)

        self.assertEqual(rows, [("claude.ai", "87.228.47.204"), ("discord.com", "23.227.38.74")])

    def test_apply_replaces_hidden_first_block_and_leaves_one_bom(self) -> None:
        # Так выглядел hosts рабочей машины: первый блок за пятью BOM, второй
        # дописан следом, потому что первый не узнавался.
        self._write(
            BOM * 5
            + f"{BEGIN}\n{NOTICE}\n87.228.47.204 claude.ai\n{END}\n\n"
            + f"{BEGIN}\n{NOTICE}\n23.227.38.74 discord.com\n{END}\n\n"
            + "142.251.14.93 www.youtube.com\n"
        )

        with (
            mock.patch.object(hosts_module.HostsManager, "is_hosts_file_accessible", return_value=True),
            mock.patch.object(hosts_module, "is_ipv6_available", return_value=False),
        ):
            ok = self._manager().apply_domain_ip_rows([("claude.ai", "87.228.47.201")])

        self.assertTrue(ok)
        raw = self.path.read_bytes().decode("utf-8")
        self.assertEqual(len(raw) - len(raw.lstrip(BOM)), 1)
        text = raw.lstrip(BOM)
        self.assertEqual(text.count(BEGIN), 1)
        self.assertNotIn("87.228.47.204", text)
        self.assertNotIn("discord.com", text)
        self.assertIn("87.228.47.201 claude.ai", text)
        self.assertIn("142.251.14.93 www.youtube.com", text)


if __name__ == "__main__":
    unittest.main()
