# Prepares a fresh clone of the repository for running.
#
# Two files are not kept in git and are therefore missing after `git clone`:
#
#   src\config\build_info.py      - version number and channel
#   src\config\_build_secrets.py  - build tokens (empty for us)
#
# The first is excluded because the build writes it. The second because it
# is a secrets file by purpose, and it must not go into the repository even
# empty: one day it will not be empty.
#
# Without them the app does not start: `from config.build_info import
# APP_VERSION` fails on the very first line. The script creates both if they
# are missing and leaves existing ones alone.
#
# ASCII only: Windows PowerShell 5.1 reads a .ps1 without BOM as ANSI, and
# the Cyrillic that used to be here turned into mojibake and broke parsing.
#
# Run from the repository root:
#   powershell -executionpolicy bypass -file scripts\bootstrap_dev.ps1

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$config = Join-Path $root "src\config"

if (-not (Test-Path $config)) {
    throw "Run from the repository root: $config not found"
}

$version = "0.15.67"

$buildInfo = Join-Path $config "build_info.py"
if (Test-Path $buildInfo) {
    Write-Host "build_info.py already exists, leaving it"
} else {
    @(
        "# Generated by the build. This is a local stub for running tests."
        "APP_VERSION = `"$version`""
        "CHANNEL = `"stable`""
    ) | Set-Content -Path $buildInfo -Encoding UTF8
    Write-Host "created build_info.py ($version)"
}

$secrets = Join-Path $config "_build_secrets.py"
if (Test-Path $secrets) {
    Write-Host "_build_secrets.py already exists, leaving it"
} else {
    @(
        '"""Generated by the build. This is an empty stub."""'
        ""
        "UPDATE_SERVERS: list[str] = []"
        'GITHUB_UPDATE_TOKEN = ""'
        'TG_UPDATE_BOT_TOKEN = ""'
        "PROXY_PRESETS: list = []"
        'MTPROXY_LINK = ""'
    ) | Set-Content -Path $secrets -Encoding UTF8
    Write-Host "created _build_secrets.py (empty)"
}

Write-Host ""
Write-Host "Next:"
Write-Host "  pip install -r requirements-runtime.txt"
Write-Host "  python src\main.py"
